### ISSUE TITLE
WalkingCat's diff engines

### ISSUE THREAD

**Issue by jzabroski** [VerifyTests/DiffEngine#180]
Hi @SimonCropp ,

Feel free to close this if you don't have interest.  I found https://github.com/WalkingCat/ today via Twitter, and he has a ton of good diff tools:

1. https://github.com/WalkingCat/SymDiff - Diff tool for comparing symbols in PDB files
2. https://github.com/WalkingCat/ExpDiff - Diff tool for comparing export tables in PE images
3. https://github.com/WalkingCat/MetaDiff - Diff tool for comparing the CLI metadata in .NET assemblies or WinMD files.
4. https://github.com/WalkingCat/ResDiff - Diff tool for comparing Win32 resources in PE images
5. https://github.com/WalkingCat/PriDiff - Diff tool for comparing resources in PRI (Package Resource Index) files

#### Is the feature request related to a problem

More features 🗡️ ❤️ 

#### Describe the solution

I am not familiar with how to implement a new DiffEngine provider.

#### Describe alternatives considered

Doing nothing.
Alternatively, for some of these, there may be Roslyn APIs and it may be better to write Verify snapshots for Roslyn API dumps instead.

**Comment by SimonCropp** [comment]
i am interested. are you using these tools?

**Comment by SimonCropp** [comment]
also an fyi. u can programmatically add your own tools https://github.com/VerifyTests/DiffEngine/blob/master/docs/diff-tool.custom.md
