### ISSUE TITLE
Beyond Compare 4 is not being detected

### ISSUE THREAD

**Issue by GeertvanHorrik** [VerifyTests/DiffEngine#22]
#### Describe the bug

Updating ApiApprover, the BeyondCompareReporter is no longer displaying beyond compare.

Discussed some on Twitter.

I am trying to repro and submit a PR.

**Comment by GeertvanHorrik** [comment]
So far it seems to do the right thing:

![image](https://user-images.githubusercontent.com/1246444/81469852-a6322b00-91e7-11ea-8f54-1392db74f5d2.png)

**Comment by GeertvanHorrik** [comment]
@SimonCropp is ApprovalsTests using a different version for the reporters?

**Comment by SimonCropp** [comment]
>  is ApprovalsTests using a different version for the reporters?

not that i know of.

Can u provide a minimal repro?

**Comment by GeertvanHorrik** [comment]
Any of the Orc libraries (such as Orc.CommandLine) have this (moved from api approve to approval tests). Will try to repro in combination with AT, but not today.

**Comment by SimonCropp** [comment]
@GeertvanHorrik i fixed the soucelinking in diffengine and approval tests. can u try debugging it on your machine again?

**Comment by SimonCropp** [comment]
u will need to update the nugets

**Comment by GeertvanHorrik** [comment]
Stuff seems to be optimized weirdly. I can step through, but once I get into the tool resolvers, the source code pdb files seems to just jump through source code.

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/81536263-8cb9ec00-936b-11ea-8494-4aa009094750.png)

As you can see, the breakpoints are somehow not working inside TryFind, as if the pdb was built against debug vs release or something.

**Comment by GeertvanHorrik** [comment]
Will do a local build of DiffEngine, I think that's easier for me to work with.

**Comment by GeertvanHorrik** [comment]
Local build works better. The issue seems to be here where Directory.EnumerateDirectories seems to return 0 items:

![image](https://user-images.githubusercontent.com/1246444/81537513-9f352500-936d-11ea-97bf-ba9617b03c50.png)

**Comment by GeertvanHorrik** [comment]
And now I see what the problem is. The unit tests are running x86, but BC is installed x64.

**Comment by GeertvanHorrik** [comment]
Maybe, but that's just an idea, it's better to add multiple paths to the diff tools resolver:

1. %programfiles%\Beyond Compare *\
2. %ProgramW6432%\Beyond Compare *\
3. %programfiles(x86)%\Beyond Compare *\

Will create a PR if you want.

**Comment by GeertvanHorrik** [comment]
Another option is to support this out of the box in the Windows resolver.

**Comment by SimonCropp** [comment]
thanks for the research. i will do a fix now

**Comment by GeertvanHorrik** [comment]
one sec, already have it fixed.

**Comment by GeertvanHorrik** [comment]
Generic fix seems to work, it "suddenly" also detects VS code:

![image](https://user-images.githubusercontent.com/1246444/81538711-6ac26880-936f-11ea-838d-d66cede65e6c.png)

**Comment by GeertvanHorrik** [comment]
here is the fix (in OsSettingsResolver.cs)

```
        if (windows != null &&
            RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            // Note: Windows can have multiple paths, and will resolve %programfiles% as 'C:\Program Files (x86)' when running inside a 32-bit process. To
            // overcome this issue, we need to manually add any option so the correct paths will be resolved

            var finalPaths = new List<string>();

            foreach (var windowsPath in windows.ExePaths)
            {
                finalPaths.Add(windowsPath);

                var lowerPath = windowsPath.ToLower();
                if (lowerPath.Contains("%programfiles%"))
                {
                    finalPaths.Add(lowerPath.Replace("%programfiles%", "%ProgramW6432%"));
                    finalPaths.Add(lowerPath.Replace("%programfiles%", "%programfiles(x86)%"));
                }
            }

            if (WildcardFileFinder.TryFindExe(windows.ExePaths, out path))
            {
                arguments = windows.Arguments;
                return true;
            }
        }
```

**Comment by SimonCropp** [comment]
ok

**Comment by GeertvanHorrik** [comment]
Sorry, you still need to pass in the finalPaths to WildCardFileFinder

**Comment by GeertvanHorrik** [comment]
Interested in a PR or can you copy/paste the fix?

**Comment by SimonCropp** [comment]
nah all good. u have done that hard work already

**Comment by SimonCropp** [comment]
ok can u try ApprovalTests/5.2.1
