### ISSUE TITLE
Allow configuring the default click action

### ISSUE THREAD

**Issue by andrewlock** [VerifyTests/DiffEngine#235]
* DiffEngineTray Version: 6.7.0+9fa4bef3082fd2ad6f7896f4a3f200b403bae808
 * OS: Microsoft Windows NT 10.0.19043.0

Would it be possible to configure the default click action for items in the diff engine tray? Currently it requires a lot of clicking and fine mouse work:

* Right click the tray icon
* Click the drop down next to the item. 9 times out of 10 (or at least if feels like it) this opens the drop down the other side of the window
* Carefully move the mouse to the drop down, making sure to not stray off the item, otherwise the drop down will close
* Click "Open diff tool"

![image](https://user-images.githubusercontent.com/18755388/124496536-72ce3a80-ddb1-11eb-9299-90222e328194.png)

**Comment by SimonCropp** [comment]
agreed. the existing behavior is horrible.

i just released 6.8.3-beta.1 that has no default action, and any click will drop down for the other options. 

can u have a try and tell me what u think?

**Comment by andrewlock** [comment]
Very nice, just given it a try and it makes it _way_ easier! Appreciate it 🙂 

The only slight annoyance now is that the drop down sometimes opens on the right, and sometimes on the left. I wonder if it would be possible to force this to be consistent (e.g. left hand size when taskbar is docked to the bottom, right hand side when docked to the left? I realise that may not be doable, just wondering 🙂

**Comment by SimonCropp** [comment]
can u try 6.8.3-beta.2

**Comment by andrewlock** [comment]
Oops, sorry, missed that one - looks good to me, I've updated to latest 🙂 Thanks again!

**Comment by SimonCropp** [comment]
@andrewlock no worries. thanks for the prompting to find a better solution
