### ISSUE TITLE
P4Merge doesn't work for the binary extensions using the current command line arguments.

### ISSUE THREAD

**Issue by matt-psaltis** [VerifyTests/DiffEngine#254]
When running a verification using
```
await Verifier.Verify(result).UseExtension("png");
```

With P4Merge installed, the following error is displayed:

`Image files cannot be merged`

The P4Merge Implementation takes four command line arguments which works correctly for text based merge operations but for binaries/images only two file paths can be passed in it seems. Additionally there doesn't currently seem to be a way to actually merge the received into the verified...

Wondering if the binary image extensions should be disabled in P4merge?

P4merge Version: r21.3

**Comment by SimonCropp** [comment]
I split the text and image parts of p4 into two different tools. I fixed the args for the image. and i moved the image varent of p4 to be lower in the order. This is deployed in diffengineand the current beta of verify

> Additionally there doesn't currently seem to be a way to actually merge the received into the verified...

There are several other ways to accept a diff https://github.com/VerifyTests/Verify#snapshot-management

**Comment by matt-psaltis** [comment]
Oh wow awesome thank you!

**Comment by SimonCropp** [comment]
i deployed a stable of Verify
