### ISSUE TITLE
Addional search path for WinMerge

### ISSUE THREAD

**Issue by cezarypiatek** [VerifyTests/DiffEngine#264]
Hi

When I install `WinMerge` using `winget` (`winget install WinMerge.WinMerge`) then the installation path is `"C:\Users\%username%\AppData\Local\Programs\WinMerge\WinMergeU.exe"` which is different than the hardcoded one. Is it possible to handle that use case?

**Comment by SimonCropp** [comment]
yep will fix when i get back to a computer

**Comment by SimonCropp** [comment]
this is deployed. i also deployed a new copy of Verify, so u should not need an explicit diffegine reference

**Comment by cezarypiatek** [comment]
Excellent works correctly. Thank you very much!
