### ISSUE TITLE
DiffTools.TryFind method is confusing

### ISSUE THREAD

**Issue by 304NotModified** [VerifyTests/DiffEngine#271]
The `DiffTools.TryFind` is a bit confusing.

#### Is the feature request related to a problem

Spot the issue:

```c#
// Add if not already there
if (!DiffTools.TryFind(name, out _))
{
    DiffTools.AddTool(name, ... );
}
```

The issue is here that:

- There is a overload of TryFind that searches by name: ` public static bool TryFind(DiffTool tool, out ResolvedTool? resolvedTool)`, while the other (with string parameter), searches by extension: `public static bool TryFind(string extension, out ResolvedTool? tool)`
- I expected that the TryFind method is consistent with the AddTool, where name is the first argument. 

#### Describe the solution

There are multiple solutions, those could be technical or semantic breaking. See the "or"s below ;)

- Add  `TryFindByExtension(string extension, ...`)
- Rename `TryFind(DiffTool tool, ...)` to  `TryFindByName(DiffTool tool, ...)`
- Add `TryFindByName(string name, ...)`
- Make `TryFind(string extension, ...)` obsolete (breaking change!)
- Make `TryFind(DiffTool tool, ...)` obsolete (breaking change!)

#### Describe alternatives considered

-  Instead of `TryFind`  rename to `TryFindTool` etc for consistency with `AddTool`
- No obsolete but hard breaking change

#### Additional context

Current work around (ugly, need Equals? Needs dictionary lookup?):

```C#
// Add if not already there
if (!DiffTools.Resolved.Any(c => c.Name == name))
{
    DiffTools.AddTool(name, ... );
}
```

**Comment by SimonCropp** [comment]
in what scenario are you using that code? is DiffEngine not finding a known tool in the correct location?

**Comment by 304NotModified** [comment]
We use the merge tool of Visual Studio, not the diffttool. (maybe I could send a PR for that in the future), also Visual Studio is installed in non-common location for me and all my colleagues.  (not my choice - but at least it's consistent 😅)

**Comment by SimonCropp** [comment]
> merge tool of Visual Studio, not the diffttool

give me the command line and i can add it

in that case shouldnt you call `DiffTools.AddTool(name, ... );` with a custom name?

**Comment by 304NotModified** [comment]
> in that case shouldnt you call `DiffTools.AddTool(name, ... );` with a custom name?

Yes of course, it was a stripped down version :)



> give me the command line and i can add it

To be clear, we currently use (still striped down version):

```c#
var vsMergePath = @"D:\Programs\Visual Studio\2022\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\vsdiffmerge.exe";
var _ = DiffTools.AddTool(
    name: "VisualStudioMerger",
    exePath: vsMergePath,
    targetLeftArguments: (received, approved) => $"\"{approved}\" \"{received}\" \"{approved}\" \"{approved}\" /m",
    targetRightArguments: (received, approved) => $"\"{approved}\" \"{received}\" \"{approved}\" \"{approved}\" /m",
    requiresTarget: true, autoRefresh: true, isMdi: true, supportsText: true, binaryExtensions: new List<string>());
```

note: I'm not sure if the targetRightArguments are correct - can find docs for targetLeftArguments / targetRightArguments

**Comment by 304NotModified** [comment]
I've updated my proposal ("Describe the solution")

**Comment by SimonCropp** [comment]
i agree in principle. can u submit a PR with your changes. then we can iterate on that if necessary

**Comment by 304NotModified** [comment]
Will try to do that this week/weekend
