### ISSUE TITLE
Visual Studio Always Used As Diff Tool, Rider and VS Code ignored

### ISSUE THREAD

**Issue by chasewallis** [VerifyTests/DiffEngine#280]
Using version 9.0.5 of DiffEngineTray, installed via `dotnet tool install -g DiffEngineTray`
Problem also exists in Rider's `Verify Support` plugin, version 2021.3.1.
Rider version 2021.2.1

When comparing received/verified (opening the diff tool), visual studio is used as the diff tool. According to [tool order](https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.order.md) documentation, I expected Rider to be used, or at least VS code.

Rider is located:
C:\Program Files\JetBrains\JetBrains Rider 2021.2.1\bin\rider64.exe
VS Code is located:
C:\Users\user_name\AppData\Local\Programs\Microsoft VS Code\code.exe

`@"%ProgramFiles%\JetBrains\JetBrains Rider *\bin\rider64.exe"` found in Rider.cs should have matched (assuming * is used as a wildcard
`@"%LocalAppData%\Programs\Microsoft VS Code\code.exe""` found in VsCode.cs should have matched vs code.

I attempted to debug, but I never cause breakpoints in those 2 files to get hit.

After running the tests from Rider, a breakpoint in PipeServer.Handle is hit with a payload like:
```
{
"Type":"Move",
"Temp":"C:\\Users\\user_name\\source\\path\\to\\tests\\testclass.execute.received.txt",
"Target":"C:\\Users\\user_name\\source\\path\\to\\tests\\testclass.execute.verified.txt",
"CanKill":false,
"Exe":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\\devenv.exe",
"Arguments":"/diff \"C:\\Users\\user_name\\source\\path\\to\\tests\\testclass.execute.received.txt\" \"C:\\Users\\user_name\\source\\path\\to\\tests\\testclass.execute.verified.txt\" \"testclass.execute.received.txt\" \"testclass.execute.verified.txt\"",
"ProcessId":60484
}
```

**Comment by SimonCropp** [comment]
can u try the latest release. u will need to update Verify as well
