### ISSUE TITLE
Fails to start with FileLoadException in logs

### ISSUE THREAD

**Issue by simon-chester** [VerifyTests/DiffEngine#284]
I installed DiffEngineTry 9.1.0 with `dotnet tool install -g DiffEngineTray`.  I try to run the tool from command line, but it does not appear. However, no error message is displayed. I found a logs folder at '.dotnet\tools\.store\diffenginetray\9.1.0\diffenginetray\9.1.0\tools\net6.0\any\logs\log.txt'.  In that I can see logs like:

2022-06-22 18:31:28.944 +01:00 [FTL] Failed at startup
System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Program.Inner()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Program.Inner()
   at Program.Main() in C:\projects\diffengine\src\DiffEngineTray\Program.cs:line 11

I'm using Windows 10 Pro (Version 10.0.19043 Build 19043).

**Comment by SimonCropp** [comment]
what dotnet verions do u have installed ? `dotnet --list-runtimes`

**Comment by simon-chester** [comment]
'dotnet --list-runtimes' outputs:
Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by SimonCropp** [comment]
looks like this
https://github.com/dotnet/winforms/issues/6663

can u try installing the latest version 6.0.6 of net6 https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by simon-chester** [comment]
Thanks. That fixed it.
