### ISSUE TITLE
Include optional environment variables for tool installer paths

### ISSUE THREAD

**Issue by jbockle** [VerifyTests/DiffEngine#296]
#### Is the feature request related to a problem

Yes, many of my diff tools are installed in their non-standard location and cannot be located

#### Describe the solution

In the list of paths to check for each diff tool, include one that is parsed from an environment variable
e.g. vscode's last search path could be something like `System.Environment.GetEnvironmentVariable("VERIFY_DIFFENGINE_VSCODE_PATH") ?? string.Empty`

#### Describe alternatives considered

I could add a new diff tool based on an existing, however I want this to be generic enough that anyone running the Verify test suite can.

#### Additional context

If you think this is a viable option I would be happen to submit a PR for it.

**Comment by SimonCropp** [comment]
the current version also scans the path environment variable. does this meet your requirements?
