### ISSUE TITLE
Cannot run Verify.Xunit tests on Windows ARM64

### ISSUE THREAD

**Issue by fleed** [VerifyTests/DiffEngine#315]
#### Describe the bug

I have a .NET 6 Xunit test project that uses the package `Verify.Xunit` (version **19.10.0**).

Other relevant versions:

- `Microsoft Visual Studio Enterprise 2022 (ARM 64-bit)` **17.4.4**
- `xunit` **2.4.2**
- `xunit.runner.visualstudio` **2.4.5**

I'm running on Windows ARM64 (under Parallels, M1 MacBook Pro).

I'm using a basic test:

```csharp
[UsesVerify]
public class VerifyTests
{
    [Fact]
    public async Task TestVerify()
    {
        var result = true;
        await Verifier.Verify(result);
    }
}
```

It fails with the following exception:

```
  Message: 
System.TypeInitializationException : The type initializer for 'DiffEngine.ProcessCleanup' threw an exception.
---- System.TypeInitializationException : The type initializer for 'System.Management.ManagementPath' threw an exception.
-------- System.TypeInitializationException : The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
------------ System.ComponentModel.Win32Exception : Failed to load required native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.

```

I cannot find information regarding the compatibility with the ARM64 architecture

**Comment by SimonCropp** [comment]
out of curiosity, why didnt you try and fix it?

**Comment by SimonCropp** [comment]
can u try v 11.2

**Comment by fleed** [comment]
Hi Simon, thank you for support.

I tried version `11.2`, but I'm getting the same error.

I hoped that it was a quick fix, but it doesn't seem so. I looked at the code and then did some search - found open issues in the dotnet runtime regarding `System.Management.ManagementObjectSearcher` not working for ARM64.

**Comment by SimonCropp** [comment]
can u share that issue?

**Comment by fleed** [comment]
This: [59844](https://github.com/dotnet/runtime/issues/59844)

**Comment by toastmastern** [comment]
Hi, followed the discussion above and the bug filed to dotnet/runtime
Is it possible to move from WMI to NtQueryInformationProcess and find command line from the PEB? (perhaps for ARM64 only)
Or wait for dotnet to fix their issue?

(i can give it a try if PRs are welcome? need to get the green dots to be considered senior dev :) )

**Comment by SimonCropp** [comment]
@toastmastern a PR that omits the WMI code on ARM64 would be greatly appreciated

**Comment by toastmastern** [comment]
Will give it a try, have had a bit shortage in hours :) noted that dotnet seems to be lack of supporting \program files (arm64), might be better to give them a day or two to solve it?

**Comment by SimonCropp** [comment]
can u try v 11.3.0

**Comment by matkoch** [comment]
Works for me

**Comment by fleed** [comment]
Works perfectly! Thank you so much @SimonCropp !
