### ISSUE TITLE
Rider version selection on macOS

### ISSUE THREAD

**Issue by slang25** [VerifyTests/DiffEngine#357]
#### Describe the bug
When running unit tests that utilise Verify under an EAP Rider version on macOS, when there is another version available results in inconsistent version selection. My hope is that when I run the tests, the current instance of Rider will be used to shell out the diff to (this is an unreasonable request), however it seems that the Rider selection is sorted by last write timestamp, which on my machine is constant flipping between the EAP and non-EAP instances. I can run two test runs, and have it pick a different version both times, seconds after the previous.

I suspect I can customize the tool selection somehow, but I would expect Verify to first resolve `rider` from my PATH and use that first, as that is what I personally use to indicate my main instance that I'm using day-to-day.

#### Minimal Repro

Install an EAP & non-EAP version of Rider, and run a test suite with differing contents. For me it happens quite inconstantly, I haven't figured out exactly when the timestamps are getting updated.

**Comment by SimonCropp** [comment]
so the code that does this is here https://github.com/VerifyTests/DiffEngine/blob/main/src/DiffEngine/OsSettingsResolver.cs#L112

so resolving by path is last. i guess that could potentially be moved to first

as for resolving different instances, i suspect that is rider making the decision on which instance to use

> My hope is that when I run the tests, the current instance of Rider will be used to shell out the diff to (

this is difficult. the parent process is `dotnet` that runs the tests. and afaik there is no env variable that rider passes through when launching `dotnet test`

**Comment by slang25** [comment]
I'm confused, because I thought that this was the order:
https://github.com/VerifyTests/DiffEngine/blob/dd898183ef6a7ae0a44629e4f509f5ff52d82107/src/DiffEngine/Implementation/Rider.cs#L27
So `rider` on the PATH should be checked first, or is it in reverse order?

**Comment by SimonCropp** [comment]
it searches all the explicit paths first. then does an env lookup

```
    static bool TryFindExe(string exeName, IEnumerable<string> searchDirectories, [NotNullWhen(true)] out string? exePath)
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            searchDirectories = ExpandProgramFiles(searchDirectories);
        }

        foreach (var directory in searchDirectories.Distinct())
        {
            var exeSearchPath = Path.Combine(directory, exeName);
            if (WildcardFileFinder.TryFind(exeSearchPath, out exePath))
            {
                return true;
            }
        }

        return TryFindInEnvPath(exeName, out exePath);
    }
```

u can define a custom location using the `DiffEngine_Rider` env variable

and i realise the docs did not match code. so i fixed that https://github.com/VerifyTests/DiffEngine/commit/812670728baaae3dbe73f2a1ba0fdee6f8490549
