### ISSUE TITLE
DiffEngineTray 'Accept all' changes all line endings from CRLF to LF

### ISSUE THREAD

**Issue by LorneCash** [VerifyTests/DiffEngine#372]
Windows 11 Pro
Visual Studio Enterprise 2022 (17.6.5)
DiffEngineTray 12.0.0

I ran my test (MSTest) and when I accept the change manually line endings stay constant but if I click the accept all button in DiffEnfineTray it changes all the line endings of the doc.verified.txt from CRLF to LF.

I'd prefer it just detects line endings for me or jsut uses CRLF automatically because it should know I'm on a Windows OS but another option would be to add a line ending option to the DiffEnfineTray settings.

In the past this never mattered to me because I always ignored whitespace when comparing files but recently I submitted a PR to a to someone else's repo and they rejected it due to me changing spaces to tabs inadvertently so now I've been leaving it on.  That's how I just noticed this now.

**Comment by SimonCropp** [comment]
> when I accept the change manually 

what do you mean by this?

**Comment by LorneCash** [comment]
@SimonCropp What I meant was, line by line in my diffing tool of choice. (VSCode)
