### ISSUE TITLE
DiffRunner.MaxInstancesToLaunch and environment variable DiffEngine_MaxInstances are in wrong order.

### ISSUE THREAD

**Issue by coenm** [VerifyTests/DiffEngine#398]
First of all, I'm not sure whether this is a bug or behavior as expected but I think it's a bug.

I'm working on a repository containing the following initialization of VerifyTest:

```cs
[ModuleInitializer]
public static void Initialize()
{
  // more code here
  DiffRunner.MaxInstancesToLaunch(int.MaxValue);
  // more code here
}
```

and I have created an environment variable `DiffEngine_MaxInstances` with the value `2`.

I expect at most two instances of my compare tool (in this case Beyond Compare) to open but it seems that the `MaxInstancesToLaunch` method precedes the environment variable value.

Possible solutions:

- Do nothing, this is as expected 
- `Math.Min(env variable DiffEngine_MaxInstances, DiffRunner.MaxInstancesToLaunch value)`
- Environment variable has precedence over `DiffRunner.MaxInstancesToLaunch`.
- Introduce second environment variable which has precedence over `DiffRunner.MaxInstanceToLaunch` (ie, environment variable `DiffEngine_ForcedMaxInstances`).

**Comment by SimonCropp** [comment]
happy to accept a pull request for this

**Comment by coenm** [comment]
What solution do you prefer?

**Comment by SimonCropp** [comment]
IMO "Environment variable has precedence over DiffRunner.MaxInstancesToLaunch." is the best approach. ie "my personal (machine) preference should override what a codebase thinks should be its default"

**Comment by coenm** [comment]
thanks for merging the PR
