### ISSUE TITLE
rider diff tool not found on linux

### ISSUE THREAD

**Issue by sleeuwen** [VerifyTests/DiffEngine#417]
#### Describe the bug

When running tests using verify from JetBrains Rider on Linux, a diff tool is selected with lower priority than Rider. I noticed the paths were changed in PR #377 because of the JetBrains Toolbox v2 update, however it looks like the path for Linux wasn't updated.

The rider.sh file is located for me in `~/.local/share/JetBrains/Toolbox/apps/rider/bin/rider.sh`, but it seems to be looking at  `~/.local/share/JetBrains/Toolbox/apps/Rider/*/*/bin/rider.sh`, which is presumably the previous location including the version number (also note the difference in casing "rider" vs "Rider", as Linux file systems are case-sensitive).

#### Minimal Repro

On any Linux distro, install JetBrains Rider from the JetBrains Toolbox. Open a project in rider and run tests using Verify from it, it will not open the diff view of Rider but of a tool with lower priority. (I'm on Arch Linux, but assume it's the same for any other distro, and using the latest version of Rider 2023.2.2)

**Comment by SimonCropp** [comment]
can u try 12.4.1

**Comment by sleeuwen** [comment]
With that version it works! Thanks!

**Comment by SimonCropp** [comment]
good to hear. BTW if you are using this tool in a commercial capacity, any amount of sponsorship would be appreciated https://github.com/sponsors/VerifyTests
