### ISSUE TITLE
ExeName for BeyondCompare on linux should be `bcompare` not `bcomp`

### ISSUE THREAD

**Issue by StudioLE** [VerifyTests/DiffEngine#423]
#### Describe the bug

The command for Beyond Compare on Linux is `bcompare` not `bcomp` as currently defined: https://github.com/VerifyTests/DiffEngine/blob/6d0f011e604c86407108762fe97f777a87b147de/src/DiffEngine/Implementation/BeyondCompare.cs#L48

This can be verified via the following documentation which shows `bcompare` as being available on Linux and Mac but `bcomp` only on Mac: https://www.scootersoftware.com/v4help/command_line_reference.html

Simple validation on Debian with a fresh install of BeyondCompare from https://www.scootersoftware.com/files/bcompare-4.4.7.28397_amd64.deb

```bash
$ which bcomp
bcomp not found
                                                                                                                                                           1 
$ which bcompare
/usr/bin/bcompare
```

#### Minimal Repro

- Install BeyondCompare https://www.scootersoftware.com/files/bcompare-4.4.7.28397_amd64.deb
- Run a test along the lines of

```csharp
internal sealed class DiffToolsTests
{
    [TestCase(DiffTool.BeyondCompare)]
    [Explicit("Requires tools to be installed")]
    public void DiffTools_Resolved(DiffTool tool)
    {
        // Arrange
        // Act
        ResolvedTool[] tools = DiffTools.Resolved.ToArray();

        // Assert
        Assert.That(tools, Is.Not.Empty);
    }
}
```

- Compared to:
```csharp


    [Test]
    [Explicit("Requires tools to be installed")]
    public void DiffTools_AddTool_BeyondCompare()
    {
        // Arrange
        LaunchArguments launchArguments = new(
            Left: (temp, target) => $"--diff \"{target}\" \"{temp}\"",
            Right: (temp, target) => $"--diff \"{temp}\" \"{target}\"");
        OsSupport osSupport = new(
            Windows: null,
            Linux: new OsSettings(
                "bcompare",
                launchArguments
            ),
            Osx: null);
        DiffTools.AddTool(
            name: "BeyondCompareLinux",
            autoRefresh: true,
            isMdi: true,
            supportsText: true,
            requiresTarget: true,
            osSupport: osSupport,
            binaryExtensions: Array.Empty<string>());

        // Act
        ResolvedTool[] tools = DiffTools.Resolved.ToArray();
        string[] toolNames = tools.Select(x => x.Name).ToArray();

        // Assert
        Assert.That(toolNames, Does.Contain("BeyondCompareLinux"));
    }
```

#### Submit a PR that fixes the bug

Submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by SimonCropp** [comment]
can u submit a PR that fixes this
