### ISSUE TITLE
Visual Studio Code installed via FlatHub is not supported on Linux

### ISSUE THREAD

**Issue by StudioLE** [VerifyTests/DiffEngine#424]
#### Describe the bug

If Visual Studio Code has been installed via FlatHub (https://flathub.org/apps/com.visualstudio.code) DiffEngine does not recognise it.

**Note: The FlatPak repackaging is not supported by Microsoft therefore it may not be expected for DiffEngine to support this. However FlatHub shows almost 2 million installs so I would expect other people to come across this issue so wanted to document a workaround.**

As a workaround you can create a bash script at `/usr/local/bin/code` with the following content and make it executable.

```
#!/bin/bash
flatpak run com.visualstudio.code "$@"
```

```bash
sudo nano /usr/local/bin/code
sudo chmod +x /usr/local/bin/code
```

Worth noting that as Visual Studio Code is running inside the FlatPak container it doesn't have access to the full file system (such as `/tmp` which may lead to unexpected "file does not exist" errors.

**Comment by SimonCropp** [comment]
for vscode on linux, currently the path environment is scanned. is this not working for you?

**Comment by SimonCropp** [comment]
then i dont know how DiffEngine can support flatpak
