### ISSUE TITLE
Rider is only supported on Linux when installed via JetBrains ToolBox

### ISSUE THREAD

**Issue by StudioLE** [VerifyTests/DiffEngine#425]
#### Describe the bug

1. When installing Rider for Linux the download page (https://www.jetbrains.com/rider/download/#section=linux) directs you towards a `.tar.gz` for manual installation.
2. Alternatively Rider can be installed (unofficially) via FlatHub (https://flathub.org/apps/com.jetbrains.Rider) (almost 50,000 installs).

Following either of these installation methods means DiffEngine is unable to locate Rider. The only supported method is installation via JetBrains Toolbox (https://www.jetbrains.com/toolbox-app/). This is perfectly acceptable but it's not entirely apparent that's the case.

**Comment by SimonCropp** [comment]
it should be failing over to discovering rider via the path environment variable. is this not working?
