### ISSUE TITLE
With Rider, when multiple tests fail, only two windows are shown (sequentially) and other tests permanently fail until IDE restart

### ISSUE THREAD

**Issue by cmeeren** [VerifyTests/DiffEngine#484]
Minimal repro solution: [TestProject.zip](https://github.com/VerifyTests/DiffEngine/files/15318020/TestProject.zip)

1. Open a single instance of Rider with the repro solution (do not open other solutions in other windows, to minimize confounders)
2. Run all tests
3. One diff window opens. Accept the changes and close.
4. Another diff window opens. Accept the changes and close.
5. **Bug:** Observe that no other diff windows open.
6. Re-run all the tests
7. **Bug:** Observe that two of the tests fail, but no diff windows open.
8. Close Rider
9. **Bug:** Observe that Rider immediately restarts, with the splash screen, and then a diff window shows. Accept the changes and close. It is possible this then repeats for the last "pending" diff window.

Using Rider 2024.1.2.

**Comment by SimonCropp** [comment]
can u try setting solution opening to "new window"

![image](https://github.com/VerifyTests/DiffEngine/assets/122666/61baac6c-e1a5-4332-9662-c89717380492)

**Comment by SimonCropp** [comment]
if that doesnt work, i think u need to `rais` it with the jetbrains peeps.

**Comment by cmeeren** [comment]
Are you sure "Reopen projects on startup" is relevant here? That is only the last bug here. Step 5 and 7 do not have anything to do with the IDE restarting.

**Comment by SimonCropp** [comment]
for me step 3 does not repro

> One diff window opens. Accept the changes and close.

when i run all tests, all diff open. 

> Are you sure "Reopen projects on startup" is relevant here

no. i am guessing

given i cant repro, i will need you to debug into it to work out what is wrong

**Comment by SimonCropp** [comment]
or, alternatively, pick a different diff tool. My preference is Beyond Compare

**Comment by SimonCropp** [comment]
also, a long shot, but i did fix a on process launching in 15.4.4. can u try that version?

**Comment by cmeeren** [comment]
> also, a long shot, but i did fix a on process launching in 15.4.4. can u try that version?

Not sure how. I use this through the [Verify support](https://plugins.jetbrains.com/plugin/17240-verify-support) plugin. So I guess that needs to be updated? Currently on version 2024.1.2 of that plugin, and I don't see an option of updating.

**Comment by SimonCropp** [comment]
> I use this through the Verify Support plugin. 

the launching of diffs during a test run is not handled by the plugin. you can get diffengine 15.4.4 by updating to Verify.Xunit 25.0.4

**Comment by cmeeren** [comment]
Thank you for the clarification. I tried updating, but there was no change in behavior. I also see that the setting "New window" was already selected.

**Comment by SimonCropp** [comment]
given DiffEngine is just [calling the rider command line](https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.md#windows-settings-8) i dont think there is much more i can do hear. I suggest you raise it with JetBrains

**Comment by SimonCropp** [comment]
perhaps @khalidabuhakmeh or @matkoch can help us

![image](https://github.com/VerifyTests/DiffEngine/assets/122666/1a9ec36e-1eae-474e-8b1b-8c1465e3a79c)

**Comment by khalidabuhakmeh** [comment]
Let me bubble this up to the right folks.

**Comment by cmeeren** [comment]
This seems to have been fixed in Rider 2024.2 (at least 2024.2.1). Thanks a lot! 😁
