### ISSUE TITLE
Vscode is not launched when test fail, just Exception is thrown

### ISSUE THREAD

**Issue by nev-21** [VerifyTests/DiffEngine#487]
#### Describe the bug

Hi, thanks for Verify and DiffEngine.

- ```Verify.Xunit 24.2.0``` 
- IDE: ```vscode 1.89.1```
- SO: ```windows 11```
- When i run the test, only ```VerifyException: ...``` appears. But vscode is not launched. I was expecting the diff between received/verified files appears in the same vscode window, or in a new window, but nothing happens. Only the exception appears.

- If I copy/paste the snapshot "received" text to "verified" file the test past, but when test fail vscode diff is not opened.

#### Minimal Repro

1. open vscode
2. create a dotnet solution 
3. create a XUnit test project  (you can use ".NET New Project" in vscode)
4. add Verify.Xunit 24.2.0 to the test project (dont forget to update other xunit nuget versions to 2.8.0)
5. make a simple test:
```
public static class StaticSettingsUsage
{
    [ModuleInitializer]
    public static void Initialize() {
        DiffTools.UseOrder(DiffTool.VisualStudioCode);
    }
}


public class UnitTest1
{
    [Fact]
    public Task Test1()
    {
        return Verify("x").UseDirectory("Snapshots");
    }
}
```

#### Submit a PR that fixes the bug

- I didn't make a PR, but I tried to understand what is happening reading DiffRunner.Launch method. I tried to call it from the test method, it doesnt work.

- I created the env var DiffEngine_VisualStudioCode with the complete literal path but it doesnt have effect.

- I used DiffTools.UseOrder(DiffTool.VisualStudioCode); in the ModuleInitializer, but it doesnt have effect too.

- I tried to use vscode as administrator, but didnt work.

Please help.

**Comment by SimonCropp** [comment]
what is the path of to VS the code exe on you machine?

**Comment by nev-21** [comment]
It is here: 
C:\Users\ct\AppData\Local\Programs\Microsoft VS Code\Code.exe

I think it is the same as "%LocalAppData%\Programs\Microsoft VS Code\"

![image](https://github.com/VerifyTests/DiffEngine/assets/89469783/4508d0bf-8322-47c8-a5b4-5d51397c9ae8)

![image](https://github.com/VerifyTests/DiffEngine/assets/89469783/360bc946-1cc6-49de-ac5e-3435d2c918cf)

**Comment by SimonCropp** [comment]
in that case i am not sure. have you tried debugging into it to see what is happening?

**Comment by nev-21** [comment]
I will try to debug by downloading the source code of Verify, I hope to find the error...

**Comment by nev-21** [comment]
Hi, I debugged DiffEngine with this code:

```cs
  [Fact]
  public async Task AddToolBasedOn()
  {
      // var wm = Implementation.WinMerge();
      // var resolvedTool = DiffTools.AddToolBasedOn(
      //     DiffTool.WinMerge,
      //     name: "MyCustomDiffTool",
      //     launchArguments: wm?.OsSupport?.Windows?.LaunchArguments!);
      
      var vscode = Implementation.VisualStudioCode();
      var resolvedTool = DiffTools.AddToolBasedOn(
          DiffTool.VisualStudioCode,
          name: "MyCustomDiffTool",
          launchArguments: vscode?.OsSupport?.Windows?.LaunchArguments!);

      await DiffRunner.LaunchAsync(resolvedTool!,@"C:\...\DiffEngine-15.4.0\license2.txt",@"C:\...\DiffEngine-15.4.0\license3.txt");
  }
```

When i use the commented part with WinMerge everything works. Winmerge is launched with the files.
But with VisualStudioCode an exception was thrown:

```The Process object must have the UseShellExecute property set to false in order to use environment variables.```

This happen because Process.Start return null process:

```cs
static int LaunchProcess(ResolvedTool tool, string arguments)
    {
        var startInfo = new ProcessStartInfo(tool.ExePath, arguments)
        {
            UseShellExecute = true
        };
        try
        {
            using var process = Process.Start(startInfo);
            if (process != null)
            {
                return process.Id;
            }

            throw new(
                $"""
                 Failed to launch diff tool.
                 {tool.ExePath} {arguments}
                 """);
        }
```

**Comment by nev-21** [comment]
I found this issue:
https://github.com/dotnet/runtime/issues/94338

and this thread:
https://stackoverflow.com/questions/63536133/creating-new-net-core-console-process-exception-when-using-environment-variabl#comment135289078_68914440

Exactly that happened to me, when i debug without touching StartInfo, the test complete ok, but vscode is not launched. When i hover over startinfo, or view that var in debug sidebar, then on Process.Start fail and return null so exception is thrown.

I noticed that when i dont touch startinfo, the process returned say "Idle" and have many error on it.
![image](https://github.com/VerifyTests/DiffEngine/assets/89469783/9c20ee8b-d07c-4b32-9438-de987bed84fd)

**Comment by nev-21** [comment]
Maybe the problem is using UseShellExecute=true

**Comment by SimonCropp** [comment]
nice research

> Maybe the problem is using UseShellExecute=true

you may be correct. i brushed up on `UseShellExecute=true` and, yeah, it should not be required in this case.

I will push a new version

**Comment by nev-21** [comment]
Thank your for your time.

- I tried the new version ```15.4.1```, and it doesnt work too.
- I debugged it again with the new version with ```UseShellExecute=false```, but vscode is not oppened.

I read this post:
https://stackoverflow.com/questions/61937342/launch-visual-studio-code-programmatically#comment137634764_61938443

So I found many ways to make vscode open:

"code" and ```UseShellExecute=true```
```cs
var startInfo = new ProcessStartInfo("code", arguments) // <------- Notice the first arg "code"
{
    // Given the full exe path is known we dont need UseShellExecute https://stackoverflow.com/a/5255335
    UseShellExecute = true,
    WindowStyle = ProcessWindowStyle.Hidden,   // <---------- this hide the cmd window that appear
};
```

"code.cmd" and ```UseShellExecute=false```
```cs
var dir = @"C:\Users\ct\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" // <---- notice the bin folder
var startInfo = new ProcessStartInfo(dir, arguments) 
{
    // Given the full exe path is known we dont need UseShellExecute https://stackoverflow.com/a/5255335
    UseShellExecute = false,
};
```

Other way was:
Changing VsCode.cs file, the "code.exe" part to "code.cmd", but i think (not 100% sure) it work because my windows environment PATH var has this; "....;C:\Users\ct\AppData\Local\Programs\Microsoft VS Code\bin;..." ( **notice bin folder**)
```cs
 return new(
            Tool: DiffTool.VisualStudioCode,
            Url: "https://code.visualstudio.com",
            AutoRefresh: true,
            IsMdi: true,
            SupportsText: true,
            RequiresTarget: true,
            Cost: "Free",
            BinaryExtensions: [".svg"],
            OsSupport: new(
                Windows: new(
                    "code.cmd", // <-----------here
                    launchArguments,
                    @"%LocalAppData%\Programs\Microsoft VS Code\",
                    @"%ProgramFiles%\Microsoft VS Code\"),
```


Please help

**Comment by SimonCropp** [comment]
but why would we use the `bin\code.cmd` when we know the exact path to the exe

```
C:\Users\SimonCropp\AppData\Local\Programs\Microsoft VS Code\Code.exe
```

we should be able to launch that exe direcly. and on my machine i can

**Comment by nev-21** [comment]
To check if there is a problem about vscode versions, or the installation I've installed vscode 1.89.1 on 2 machines (appart of my machine).

- All of them create the PATH envvar ```C:\Users\....\AppData\Local\Programs\Microsoft VS Code\bin```
- When you press Win+R and write **code.exe** it doesnt execute (an error dialog appear)
- When you press Win+R and write **code or code.cmd** vscode is opened
- I you double click on Code.exe or shortcut it opens normally.


Also, In this [answer](https://stackoverflow.com/questions/61937342/launch-visual-studio-code-programmatically#comment109552307_61938443) I found a [link ](https://learn.microsoft.com/es-es/windows/win32/shell/app-registration#finding-an-application-executable) that shows many way an exe could be registered and found. Maybe the way I install vscode is bad, or you have Code.exe registered in some special way.

So, my thoughts are:
- the way vscode is opened should be a way that work on any machine
- if cmd way works for you maybe that is the way.
- another solution is the nuget consumer should specify in which way he wants to open vscode (exe or cmd) maybe with an env var.
- I don't know why code.exe doesnt work with process.start in many machines with clean vscode install.

**Comment by nev-21** [comment]
Please help @SimonCropp, what do you think about using an env-var to open with ```bin\code.cmd``` ?

**Comment by SimonCropp** [comment]
diffengine tracks launched processes, and then closes them when the change is accepted. calling a script that launches the exe would break that behavior.

given i cant reproduce this. your best bet is to work out what the problem is yourself and submit a pull request that fixes it.

or, alternatively, move to a different diff tool like beyond compare

**Comment by nev-21** [comment]
ok thank you @SimonCropp I'm using winmerge
